### ISSUE TITLE
error

### ISSUE THREAD

**Issue by starbreaker667** [nrandell/dallasng#1]
Library Manager: Installing ESP8266WiFi
INFO Installing ESP8266WiFi
Library Manager: Installing git+https://github.com/pstolarz/OneWireNg @ 0.12.0
INFO Installing git+https://github.com/pstolarz/OneWireNg @ 0.12.0
git version 2.30.2
Cloning into '/data/cache/platformio/cache/tmp/pkg-installing-l0r8jv_7'...
Error: Package version 0.12.1+sha.b2fef2d doesn't satisfy requirements 0.12.0 based on PackageMetaData <type=library name=OneWireNg version=0.12.1+sha.b2fef2d spec={'owner': None, 'id': None, 'name': 'OneWireNg', 'requirements': '0.12.0', 'uri': 'git+https://github.com/pstolarz/OneWireNg'}

**Comment by nrandell** [comment]
I believe this should now be fixed by upgrading the OneWireNg library reference to 0.12.1
