### ISSUE TITLE
Interrupt disabling on temperature conversion

### ISSUE THREAD

**Issue by pstolarz** [nrandell/dallasng#6]
I propose to remove this line:
https://github.com/nrandell/dallasng/blob/4a915630199dd4cfca324f68053fd43df8a16fc8/components/dallasng/dallasng_component.cpp#L101

The library itself takes care about handling critical sections where it's absolutely required, therefore additional protection shouldn't be introduced in the user's code (not mentioning it depletes platform performance especially with WiFi turned on).

BTW: Thanks for using my lib on ESP. I hope it's working fine.

**Comment by nrandell** [comment]
Thanks for this. As far as I can tell the library works well. I've had quite a few people using it!
